import type {
  DriverId, Flow, Rate, ResourceId, SeasonProfileId, SystemDef,
} from './types';

/* ---------- terse authoring helpers ---------- */

const flat = (perUnitPerMonth: number): Rate => ({ kind: 'constant', perUnitPerMonth });
const yearly = (perUnitPerYear: number, season: SeasonProfileId = 'flat'): Rate =>
  ({ kind: 'annual', perUnitPerYear, season });
const driven = (driver: DriverId, coefficient: number): Rate =>
  ({ kind: 'driver', driver, coefficient });

const out = (resource: ResourceId, rate: Rate): Flow =>
  ({ resource, direction: 'produce', rate });
const need = (resource: ResourceId, rate: Rate, optional = false): Flow =>
  ({ resource, direction: 'consume', rate, ...(optional ? { optional: true } : {}) });

/**
 * The starter catalog.
 *
 * Nothing here ships as `proven`: proven means *you* built it and measured it
 * on this site, which no shipped default can claim. Everything credible and
 * well documented is `researched`; everything speculative, contested or so
 * site-dependent that a yard-scale figure is close to meaningless is
 * `experimental`, and the engine's low case assumes those barely work.
 *
 * Promote entries in the Catalog tab as you build and log them.
 */
export const CATALOG: SystemDef[] = [
  /* ============================ WATER ============================ */
  {
    id: 'roof-catchment',
    name: 'Roof catchment',
    category: 'water',
    evidence: 'researched',
    summary: 'Gutters and downpipes feeding a tank. 1 mm of rain on 1 m² of roof is 1 litre, minus first flush and splash.',
    unitLabel: 'm² of roof',
    unitDefault: 60, unitMin: 5, unitMax: 500, unitStep: 5,
    footprintPerUnit: 0,
    roofFootprintPerUnit: 1,
    siting: ['roof'],
    capitalPerUnit: 12,
    upkeepCostPerUnitPerMonth: 0.02,
    flows: [
      out('waterIrrigation', driven('rainfallMm', 0.85)),
      need('labor', flat(0.004)),
    ],
    notes: 'Runoff coefficient 0.85 covers first-flush diversion and wetting losses on a hard roof. Catchment without storage is nearly useless — pair it with a tank and watch the dry-season line in Results.',
    sources: ['Brad Lancaster, Rainwater Harvesting for Drylands and Beyond', 'Texas Water Development Board, Rainwater Harvesting Manual'],
  },
  {
    id: 'poly-tank',
    name: 'Polyethylene water tank',
    category: 'water',
    evidence: 'researched',
    summary: 'Off-the-shelf above-ground storage. The single biggest lever on dry-season resilience.',
    unitLabel: 'm³ of storage',
    unitDefault: 5, unitMin: 0.2, unitMax: 60, unitStep: 0.5,
    footprintPerUnit: 1.1,
    siting: ['openGround', 'nearHouse'],
    capitalPerUnit: 260,
    upkeepCostPerUnitPerMonth: 0.05,
    flows: [need('labor', flat(0.05))],
    storage: { resource: 'waterIrrigation', capacityPerUnit: 1000 },
    notes: 'Sized in m³ because that is how you buy it: 1 m³ = 1000 L. Cost per litre falls sharply above ~5 m³.',
    sources: ['Trade pricing, 2024 range'],
  },
  {
    id: 'ferrocement-cistern',
    name: 'Ferrocement / block cistern',
    category: 'water',
    evidence: 'researched',
    summary: 'Site-built storage, usually partly buried. Cheaper per litre at volume, much more of your own labour.',
    unitLabel: 'm³ of storage',
    unitDefault: 10, unitMin: 1, unitMax: 120, unitStep: 1,
    footprintPerUnit: 0.9,
    siting: ['openGround'],
    capitalPerUnit: 130,
    upkeepCostPerUnitPerMonth: 0.03,
    flows: [need('labor', flat(0.12))],
    storage: { resource: 'waterIrrigation', capacityPerUnit: 1000 },
    notes: 'Build quality decides whether this lasts thirty years or leaks in two. The labour figure assumes you build it yourself over a season.',
    sources: ['Watt, Ferrocement Water Tanks and Their Construction'],
  },
  {
    id: 'swale-berm',
    name: 'Swale & berm earthworks',
    category: 'water',
    evidence: 'researched',
    summary: 'On-contour ditches that stop runoff and push it into the soil profile, where planted areas can reach it.',
    unitLabel: 'm² of catchment served',
    unitDefault: 120, unitMin: 10, unitMax: 2000, unitStep: 10,
    footprintPerUnit: 0.15,
    siting: ['openGround', 'lowPoint'],
    capitalPerUnit: 1.5,
    upkeepCostPerUnitPerMonth: 0,
    flows: [
      out('waterIrrigation', driven('rainfallMm', 0.25)),
      need('labor', flat(0.002)),
    ],
    notes: 'Credited at 25% of incident rain — the share that would otherwise leave as runoff and instead becomes plant-available soil moisture. On sand the gain is smaller and on heavy clay a badly cut swale can waterlog; both are why this is not `proven` until you have dug one here.',
    sources: ['Lancaster, Rainwater Harvesting for Drylands', 'Yeomans, Water for Every Farm'],
  },
  {
    id: 'greywater-branched-drain',
    name: 'Branched-drain greywater',
    category: 'water',
    evidence: 'researched',
    summary: 'Gravity-fed laundry/shower water split to mulch basins around trees. No pump, no filter, no tank.',
    unitLabel: 'outlets',
    unitDefault: 4, unitMin: 1, unitMax: 20, unitStep: 1,
    footprintPerUnit: 2,
    siting: ['nearHouse', 'openGround'],
    capitalPerUnit: 90,
    upkeepCostPerUnitPerMonth: 0.5,
    flows: [
      need('greywater', flat(1800)),
      out('waterIrrigation', flat(1710)),
      need('labor', flat(0.3)),
    ],
    notes: 'Each outlet handles roughly 60 L/day. Never stored, never pressurised — that is what keeps it legal in most jurisdictions and safe without treatment. Check local code before building.',
    sources: ['Art Ludwig, Create an Oasis with Greywater'],
  },
  {
    id: 'constructed-wetland',
    name: 'Constructed wetland',
    category: 'water',
    evidence: 'researched',
    summary: 'Subsurface-flow gravel bed planted with reeds; polishes greywater to a quality you can store and drip-irrigate with.',
    unitLabel: 'm² of bed',
    unitDefault: 8, unitMin: 2, unitMax: 60, unitStep: 1,
    footprintPerUnit: 1.2,
    siting: ['openGround', 'lowPoint', 'fullSun'],
    capitalPerUnit: 110,
    upkeepCostPerUnitPerMonth: 0.2,
    flows: [
      need('greywater', flat(1200)),
      out('waterIrrigation', flat(1080)),
      need('labor', flat(0.15)),
    ],
    notes: 'Sizing rule of thumb is 1–2 m² per person for greywater only. Performance drops hard below about 8 °C, which the model does not yet penalise — treat winter output as optimistic in cold climates.',
    sources: ['US EPA, Constructed Wetlands Treatment of Municipal Wastewaters'],
  },
  {
    id: 'slow-sand-filter',
    name: 'Slow sand filter + storage',
    category: 'water',
    evidence: 'researched',
    summary: 'Biological filtration turning stored rainwater into drinking-grade water without power.',
    unitLabel: 'filters',
    unitDefault: 1, unitMin: 1, unitMax: 6, unitStep: 1,
    footprintPerUnit: 1.5,
    siting: ['nearHouse'],
    capitalPerUnit: 350,
    upkeepCostPerUnitPerMonth: 2,
    flows: [
      need('waterIrrigation', flat(9000)),
      out('waterPotable', flat(8500)),
      need('labor', flat(1.2)),
    ],
    notes: 'About 300 L/day through a household-scale unit once the schmutzdecke has matured. Bacteriological performance is good; it does nothing for dissolved chemistry. Test before you trust it.',
    sources: ['WHO, Household Water Treatment and Safe Storage', 'CAWST biosand filter manuals'],
  },
  {
    id: 'uv-ro-treatment',
    name: 'Cartridge + UV treatment',
    category: 'water',
    evidence: 'researched',
    summary: 'Sediment and carbon cartridges plus a UV lamp. Reliable, needs power and a consumables budget.',
    unitLabel: 'units',
    unitDefault: 1, unitMin: 1, unitMax: 4, unitStep: 1,
    footprintPerUnit: 0.4,
    siting: ['indoor', 'nearHouse'],
    capitalPerUnit: 520,
    upkeepCostPerUnitPerMonth: 11,
    flows: [
      need('waterIrrigation', flat(15000)),
      out('waterPotable', flat(14700)),
      need('electricity', flat(14)),
      need('labor', flat(0.4)),
    ],
    notes: 'The UV lamp draws continuously, so this is a real load on an off-grid array. Cartridge cost is the number people forget.',
    sources: ['Manufacturer duty ratings for domestic UV units'],
  },
  {
    id: 'drip-irrigation',
    name: 'Drip irrigation & timer',
    category: 'water',
    evidence: 'researched',
    summary: 'Delivers water at the root zone instead of over the leaves. Credited as water it saves on the beds it serves.',
    unitLabel: 'm² of bed served',
    unitDefault: 40, unitMin: 5, unitMax: 500, unitStep: 5,
    footprintPerUnit: 0,
    siting: ['openGround'],
    capitalPerUnit: 3.5,
    upkeepCostPerUnitPerMonth: 0.01,
    flows: [
      out('waterIrrigation', driven('irrigationDemandPerM2', 0.35)),
      need('labor', flat(0.004)),
    ],
    notes: 'Modelled as a 35% cut in the irrigation a bed would otherwise need versus hand or sprinkler watering. Only credit the area you actually pipe.',
    sources: ['FAO Irrigation and Drainage Paper 56', 'Extension trials on drip vs sprinkler efficiency'],
  },
  {
    id: 'sheet-mulch',
    name: 'Deep mulch',
    category: 'water',
    evidence: 'researched',
    summary: 'Several inches of coarse organic matter over bare soil. Cuts evaporation, feeds soil life, suppresses weeds.',
    unitLabel: 'm² mulched',
    unitDefault: 60, unitMin: 5, unitMax: 800, unitStep: 5,
    footprintPerUnit: 0,
    siting: ['openGround'],
    capitalPerUnit: 1.2,
    upkeepCostPerUnitPerMonth: 0.01,
    flows: [
      out('waterIrrigation', driven('irrigationDemandPerM2', 0.25)),
      need('biomass', yearly(2.5)),
      need('labor', flat(0.01)),
    ],
    notes: 'Stacks with drip: mulch cuts evaporative loss, drip cuts delivery loss. It eats biomass every year, which is why a chop-and-drop or coppice source belongs in the same design.',
    sources: ['Extension mulching trials', 'Ruth Stout, Gardening Without Work'],
  },
  {
    id: 'hand-well',
    name: 'Shallow well & hand pump',
    category: 'water',
    evidence: 'researched',
    summary: 'A hand-pumped shallow well: independent of both rainfall and the grid.',
    unitLabel: 'wells',
    unitDefault: 1, unitMin: 1, unitMax: 3, unitStep: 1,
    footprintPerUnit: 3,
    siting: ['openGround', 'lowPoint'],
    capitalPerUnit: 2600,
    upkeepCostPerUnitPerMonth: 3,
    flows: [
      out('waterIrrigation', flat(9000)),
      need('labor', flat(4)),
    ],
    notes: 'Whether you have a shallow aquifer at all is a site fact, not a design choice — the yield here is a placeholder until you have drilled and drawn down a test hole.',
    sources: ['Village-scale handpump yield ranges'],
  },
  {
    id: 'atmospheric-water',
    name: 'Atmospheric water generator',
    category: 'water',
    evidence: 'experimental',
    summary: 'Condenses drinking water out of the air. Works; the question is what it costs you in kWh.',
    unitLabel: 'units',
    unitDefault: 1, unitMin: 1, unitMax: 4, unitStep: 1,
    footprintPerUnit: 0.8,
    siting: ['nearHouse', 'indoor'],
    capitalPerUnit: 1900,
    upkeepCostPerUnitPerMonth: 6,
    flows: [
      out('waterPotable', flat(450)),
      need('electricity', flat(135)),
      need('labor', flat(0.5)),
    ],
    notes: 'Around 0.3 kWh per litre in warm humid air, and far worse when it is cold or dry — exactly the conditions where you would need it. Almost never beats a tank on cost per litre. Kept in the catalog so you can prove that to yourself.',
    sources: ['Manufacturer specifications at 30 °C / 80% RH, which field conditions rarely match'],
  },
  {
    id: 'fog-net',
    name: 'Fog harvesting net',
    category: 'water',
    evidence: 'experimental',
    summary: 'Mesh panels that strip droplets out of moving fog. Spectacular where it works, useless where it does not.',
    unitLabel: 'm² of mesh',
    unitDefault: 10, unitMin: 2, unitMax: 200, unitStep: 2,
    footprintPerUnit: 0.3,
    siting: ['openGround'],
    capitalPerUnit: 45,
    upkeepCostPerUnitPerMonth: 0.1,
    flows: [
      out('waterIrrigation', flat(90)),
      need('labor', flat(0.05)),
    ],
    notes: 'Documented yields span 0.5 to 10 L/m²/day depending entirely on fog frequency and wind — a range so wide the average is meaningless. Only a year of measurement on your ridge turns this into a real number.',
    sources: ['FogQuest field reports', 'Published coastal fog-collection studies'],
  },

  /* ============================ ENERGY ============================ */
  {
    id: 'solar-pv',
    name: 'Solar PV array',
    category: 'energy',
    evidence: 'researched',
    summary: 'The best-characterised system in this catalog: output is a physics problem, not an opinion.',
    unitLabel: 'kW installed',
    unitDefault: 4, unitMin: 0.2, unitMax: 30, unitStep: 0.2,
    footprintPerUnit: 0,
    roofFootprintPerUnit: 6,
    siting: ['roof', 'fullSun'],
    capitalPerUnit: 1150,
    upkeepCostPerUnitPerMonth: 0.6,
    flows: [
      out('electricity', driven('peakSunHours', 0.78)),
      need('labor', flat(0.06)),
    ],
    notes: 'The 0.78 derate covers inverter losses, temperature, soiling and wiring — the same figure PVWatts uses by default. Charged against roof area at 6 m² per kW; a ground mount trades that for the same area of yard, plus spacing so the rows do not shade each other.',
    sources: ['NREL PVWatts default system losses', 'Installed cost surveys, residential scale'],
  },
  {
    id: 'battery-bank',
    name: 'Battery bank',
    category: 'energy',
    evidence: 'researched',
    summary: 'LiFePO4 storage. Carries you across nights and cloudy runs, not across a season.',
    unitLabel: 'kWh usable',
    unitDefault: 10, unitMin: 1, unitMax: 100, unitStep: 1,
    footprintPerUnit: 0.05,
    siting: ['indoor', 'nearHouse'],
    capitalPerUnit: 340,
    upkeepCostPerUnitPerMonth: 0.1,
    flows: [need('labor', flat(0.02))],
    storage: { resource: 'electricity', capacityPerUnit: 1 },
    notes: 'A monthly model flatters batteries: it cannot see a five-day storm. Read the electricity result as "is there enough energy in the month", and size the bank on days of autonomy separately.',
    sources: ['LiFePO4 residential pack pricing, 2024 range'],
  },
  {
    id: 'solar-thermal',
    name: 'Solar hot water',
    category: 'energy',
    evidence: 'researched',
    summary: 'Flat-plate or evacuated-tube collectors. Far more efficient per m² than PV when what you want is heat.',
    unitLabel: 'm² of collector',
    unitDefault: 4, unitMin: 1, unitMax: 20, unitStep: 1,
    footprintPerUnit: 0,
    roofFootprintPerUnit: 1,
    siting: ['roof', 'fullSun'],
    capitalPerUnit: 480,
    upkeepCostPerUnitPerMonth: 0.5,
    flows: [
      out('heat', driven('peakSunHours', 0.45)),
      need('electricity', flat(2)),
      need('labor', flat(0.1)),
    ],
    notes: '45% net collector efficiency across the year. Output is capped in practice by your tank and your draw — surplus in July is not usable in January.',
    sources: ['Solar Keymark collector test data ranges'],
  },
  {
    id: 'rocket-mass-heater',
    name: 'Rocket mass heater',
    category: 'energy',
    evidence: 'researched',
    summary: 'A very clean-burning J-tube feeding a thermal mass bench that radiates for hours after the fire is out.',
    unitLabel: 'heaters',
    unitDefault: 1, unitMin: 1, unitMax: 3, unitStep: 1,
    footprintPerUnit: 3,
    siting: ['indoor'],
    capitalPerUnit: 900,
    upkeepCostPerUnitPerMonth: 1,
    flows: [
      out('heat', driven('heatingDegreeDays', 1.15)),
      need('biomass', driven('heatingDegreeDays', 0.33)),
      need('labor', driven('heatingDegreeDays', 0.012)),
    ],
    notes: 'Roughly 3.5 kWh of usable heat per kg of dry wood — high, because the mass captures flue heat a stove sends up the chimney. Needs dry fuel and daily tending; both are in the numbers. Building code and insurance treat these as owner-built appliances.',
    sources: ['Wisner & Evans, Rocket Mass Heaters', 'Published RMH emissions and efficiency testing'],
  },
  {
    id: 'coppice-woodlot',
    name: 'Coppice woodlot',
    category: 'energy',
    evidence: 'researched',
    summary: 'Fast-regrowing hardwood cut on rotation. The only genuinely renewable fuel a yard can grow.',
    unitLabel: 'm² of coppice',
    unitDefault: 200, unitMin: 20, unitMax: 5000, unitStep: 20,
    footprintPerUnit: 1,
    siting: ['openGround', 'partShade'],
    capitalPerUnit: 1.8,
    upkeepCostPerUnitPerMonth: 0,
    flows: [
      out('biomass', yearly(0.8, 'winter')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.15)),
      need('labor', yearly(0.02, 'winter')),
    ],
    notes: '0.8 kg dry wood per m² per year is a temperate mid-range for willow, hazel or alder on decent ground; halve it on thin dry soil. First harvest is three to seven years out, which no annual figure conveys.',
    sources: ['UK short-rotation coppice yield trials', 'Rackham, Ancient Woodland'],
  },
  {
    id: 'solar-dehydrator',
    name: 'Solar dehydrator',
    category: 'energy',
    evidence: 'researched',
    summary: 'Sun-driven drying rack. Cheap, simple, and the difference between a glut and a pantry.',
    unitLabel: 'm² of tray',
    unitDefault: 2, unitMin: 0.5, unitMax: 12, unitStep: 0.5,
    footprintPerUnit: 1,
    siting: ['fullSun'],
    capitalPerUnit: 70,
    upkeepCostPerUnitPerMonth: 0.1,
    flows: [
      out('heat', driven('peakSunHours', 0.2)),
      need('labor', flat(0.6)),
    ],
    notes: 'Counted as displaced process heat rather than food, since it preserves calories you already grew instead of creating new ones.',
    sources: ['Appropriate-technology dryer designs'],
  },
  {
    id: 'biogas-digester',
    name: 'Biogas digester',
    category: 'energy',
    evidence: 'researched',
    summary: 'Sealed anaerobic tank turning manure, blackwater and food waste into cooking gas plus liquid fertiliser.',
    unitLabel: 'm³ of digester',
    unitDefault: 2, unitMin: 1, unitMax: 20, unitStep: 1,
    footprintPerUnit: 2.5,
    siting: ['openGround', 'fullSun'],
    capitalPerUnit: 620,
    upkeepCostPerUnitPerMonth: 1,
    flows: [
      need('organicWaste', flat(45)),
      need('blackwater', flat(150), true),
      out('heat', flat(60)),
      out('compost', flat(18)),
      need('labor', flat(1.5)),
    ],
    notes: 'Gas production collapses below about 20 °C, so in a cold climate this is a summer-only system unless the digester is heated or buried deep. The model does not apply that penalty yet — read cold-climate output as optimistic.',
    sources: ['Home Biogas / ARTI digester field data', 'FAO biogas technology handbooks'],
  },
  {
    id: 'micro-wind',
    name: 'Small wind turbine',
    category: 'energy',
    evidence: 'experimental',
    summary: 'A yard-height turbine. Almost always underperforms its brochure, and here is why.',
    unitLabel: 'kW rated',
    unitDefault: 1, unitMin: 0.2, unitMax: 10, unitStep: 0.2,
    footprintPerUnit: 12,
    siting: ['openGround'],
    capitalPerUnit: 2400,
    upkeepCostPerUnitPerMonth: 4,
    flows: [
      out('electricity', flat(58)),
      need('labor', flat(0.8)),
    ],
    notes: 'Power goes as the cube of wind speed, and wind speed near buildings and trees is a fraction of the open-field figure the rating assumes. Field studies of urban and suburban installs routinely find capacity factors under 10% — that is the 58 kWh/kW/month here, and it may still be generous for your site. Measure a year of wind at hub height before spending anything.',
    sources: ['Warwick Wind Trials', 'Encraft urban wind field study'],
  },
  {
    id: 'micro-hydro',
    name: 'Micro-hydro',
    category: 'energy',
    evidence: 'experimental',
    summary: 'The best off-grid power source in existence — if you happen to own falling water.',
    unitLabel: 'W of continuous output',
    unitDefault: 200, unitMin: 20, unitMax: 3000, unitStep: 20,
    footprintPerUnit: 0.02,
    siting: ['lowPoint'],
    capitalPerUnit: 6,
    upkeepCostPerUnitPerMonth: 0.02,
    flows: [
      out('electricity', flat(0.7)),
      need('labor', flat(0.01)),
    ],
    notes: 'Runs day and night, which makes a 200 W turbine worth more than 2 kW of panels. But output is set entirely by head and flow on your land, and both vary by season and by drought. Unproven until you have measured litres per second and metres of fall yourself — and checked who owns the water rights.',
    sources: ['Harvey, Micro-Hydro Design Manual'],
  },
  {
    id: 'wood-gasifier',
    name: 'Wood gasifier generator',
    category: 'energy',
    evidence: 'experimental',
    summary: 'Partial combustion of wood into producer gas, run through a converted engine-generator.',
    unitLabel: 'kW of genset',
    unitDefault: 3, unitMin: 1, unitMax: 15, unitStep: 1,
    footprintPerUnit: 4,
    siting: ['openGround'],
    capitalPerUnit: 1700,
    upkeepCostPerUnitPerMonth: 12,
    flows: [
      out('electricity', flat(24)),
      need('biomass', flat(30)),
      need('labor', flat(6)),
    ],
    notes: 'Proven at wartime scale, awkward at yard scale: tar fouling, constant tending, and carbon monoxide that has killed people running one indoors. About 1 kWh per kg of dry wood at the socket. Real, but treat the labour and the hazard as the actual cost.',
    sources: ['FEMA Construction of a Simplified Wood Gas Generator', 'All Power Labs documentation'],
  },

  /* ============================ FOOD ============================ */
  {
    id: 'annual-beds',
    name: 'Annual vegetable beds',
    category: 'food',
    evidence: 'researched',
    summary: 'Ordinary well-run kitchen-garden beds: salad, brassicas, roots, beans, tomatoes.',
    unitLabel: 'm² of bed',
    unitDefault: 40, unitMin: 2, unitMax: 1000, unitStep: 2,
    footprintPerUnit: 1.35,
    siting: ['fullSun', 'openGround'],
    capitalPerUnit: 18,
    upkeepCostPerUnitPerMonth: 0.06,
    flows: [
      out('foodCalories', yearly(950, 'growing')),
      out('foodProtein', yearly(0.055, 'growing')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 1)),
      need('compost', yearly(4)),
      need('labor', yearly(1.6, 'growing')),
    ],
    notes: 'About 3 kg of mixed veg per m² per year at roughly 320 kcal/kg. Vegetables are nutrition, not calories — the model will show you plainly that a salad garden barely dents a calorie target. Footprint includes paths.',
    sources: ['Extension home-garden yield tables', 'Coleman, The New Organic Grower'],
  },
  {
    id: 'staple-potato-bed',
    name: 'Staple bed — potatoes',
    category: 'food',
    evidence: 'researched',
    summary: 'The highest-calorie thing a temperate yard can grow per square metre, by a wide margin.',
    unitLabel: 'm² of bed',
    unitDefault: 30, unitMin: 2, unitMax: 1000, unitStep: 2,
    footprintPerUnit: 1.25,
    siting: ['fullSun', 'openGround'],
    capitalPerUnit: 8,
    upkeepCostPerUnitPerMonth: 0.04,
    flows: [
      out('foodCalories', yearly(3100, 'growing')),
      out('foodProtein', yearly(0.09, 'growing')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.9)),
      need('compost', yearly(3)),
      need('labor', yearly(0.9, 'growing')),
    ],
    notes: '4 kg/m² at 770 kcal/kg. Blight risk and the need to rotate are the reasons the real multi-year average sits below the good-year figure.',
    sources: ['Extension potato yield ranges', 'USDA nutrient database'],
  },
  {
    id: 'winter-squash',
    name: 'Winter squash & pumpkin',
    category: 'food',
    evidence: 'researched',
    summary: 'Sprawling, low-effort calories that store for months without processing or power.',
    unitLabel: 'm² of bed',
    unitDefault: 25, unitMin: 2, unitMax: 500, unitStep: 1,
    footprintPerUnit: 1.1,
    siting: ['fullSun', 'openGround'],
    capitalPerUnit: 5,
    upkeepCostPerUnitPerMonth: 0.02,
    flows: [
      out('foodCalories', yearly(1350, 'growing')),
      out('foodProtein', yearly(0.045, 'growing')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.85)),
      need('compost', yearly(2.5)),
      need('labor', yearly(0.5, 'growing')),
    ],
    notes: 'Storage is the real feature: a dry shelf and no electricity gets you to spring.',
    sources: ['Extension cucurbit yield tables'],
  },
  {
    id: 'biointensive-bed',
    name: 'Biointensive deep bed',
    category: 'food',
    evidence: 'researched',
    summary: 'Double-dug, close-spaced, compost-driven beds aiming at calorie and compost self-sufficiency together.',
    unitLabel: 'm² of bed',
    unitDefault: 40, unitMin: 4, unitMax: 800, unitStep: 4,
    footprintPerUnit: 1.15,
    siting: ['fullSun', 'openGround'],
    capitalPerUnit: 14,
    upkeepCostPerUnitPerMonth: 0.05,
    flows: [
      out('foodCalories', yearly(2400, 'growing')),
      out('foodProtein', yearly(0.11, 'growing')),
      out('biomass', yearly(1.2, 'growing')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.75)),
      need('compost', yearly(9)),
      need('labor', yearly(4.5, 'growing')),
    ],
    notes: 'The published yields assume years of soil building and a lot of skilled hands — note the labour line, which is roughly triple ordinary beds. The compost appetite is deliberate: the method grows much of its own fertility in the same bed.',
    sources: ['Jeavons, How to Grow More Vegetables', 'Ecology Action research summaries'],
  },
  {
    id: 'hugelkultur',
    name: 'Hügelkultur mound',
    category: 'food',
    evidence: 'researched',
    summary: 'Beds built over buried decaying wood that acts as a sponge and a slow fertiliser.',
    unitLabel: 'm² of mound',
    unitDefault: 20, unitMin: 2, unitMax: 400, unitStep: 2,
    footprintPerUnit: 1.3,
    siting: ['fullSun', 'openGround'],
    capitalPerUnit: 6,
    upkeepCostPerUnitPerMonth: 0.02,
    flows: [
      out('foodCalories', yearly(850, 'growing')),
      out('foodProtein', yearly(0.05, 'growing')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.5)),
      need('biomass', yearly(6)),
      need('compost', yearly(2)),
      need('labor', yearly(1.4, 'growing')),
    ],
    notes: 'Credited with half the irrigation demand of a flat bed. Expect a nitrogen-poor first year while the buried wood colonises — the annual average hides that.',
    sources: ['Sepp Holzer, Permaculture', 'Extension observations on wood-core beds'],
  },
  {
    id: 'polytunnel',
    name: 'Polytunnel / hoop house',
    category: 'food',
    evidence: 'researched',
    summary: 'Unheated cover that buys weeks at both ends of the season and a warmer summer crop.',
    unitLabel: 'm² covered',
    unitDefault: 20, unitMin: 5, unitMax: 300, unitStep: 5,
    footprintPerUnit: 1.2,
    siting: ['fullSun', 'openGround'],
    capitalPerUnit: 65,
    upkeepCostPerUnitPerMonth: 0.15,
    flows: [
      out('foodCalories', yearly(2100, 'flat')),
      out('foodProtein', yearly(0.12, 'flat')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 1.25)),
      need('compost', yearly(7)),
      need('labor', yearly(3.2)),
    ],
    notes: 'The flat seasonal profile is the point: a tunnel spreads output into the shoulder months instead of piling it into August. Higher water demand because rain never lands on the bed. Plastic is a five-to-eight year consumable.',
    sources: ['Coleman, Four-Season Harvest', 'Extension high-tunnel trials'],
  },
  {
    id: 'food-forest',
    name: 'Food forest guild',
    category: 'food',
    evidence: 'researched',
    summary: 'Layered perennial planting — canopy, shrub, herb, root. Low yield per m², very low input once established.',
    unitLabel: 'm² planted',
    unitDefault: 100, unitMin: 10, unitMax: 3000, unitStep: 10,
    footprintPerUnit: 1,
    siting: ['fullSun', 'partShade', 'openGround'],
    capitalPerUnit: 9,
    upkeepCostPerUnitPerMonth: 0.01,
    flows: [
      out('foodCalories', yearly(600, 'growing')),
      out('foodProtein', yearly(0.03, 'growing')),
      out('biomass', yearly(0.6)),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.35)),
      need('labor', yearly(0.35)),
    ],
    notes: 'The honest caveat: yields are near zero for the first three to five years and this figure is the mature state. Published per-m² numbers vary by an order of magnitude depending on what people count.',
    sources: ['Jacke & Toensmeier, Edible Forest Gardens', 'Crawford, Creating a Forest Garden'],
  },
  {
    id: 'fruit-trees',
    name: 'Fruit trees',
    category: 'food',
    evidence: 'researched',
    summary: 'Semi-dwarf apple, pear, plum. Decades of calories for an hour of pruning a year.',
    unitLabel: 'trees',
    unitDefault: 6, unitMin: 1, unitMax: 100, unitStep: 1,
    footprintPerUnit: 16,
    siting: ['fullSun', 'openGround'],
    capitalPerUnit: 45,
    upkeepCostPerUnitPerMonth: 0.2,
    flows: [
      out('foodCalories', yearly(20000, 'growing')),
      out('foodProtein', yearly(0.25, 'growing')),
      out('biomass', yearly(4, 'winter')),
      need('waterIrrigation', flat(220)),
      need('labor', yearly(3)),
    ],
    notes: 'A mature semi-dwarf gives roughly 40 kg at 500 kcal/kg. Biennial bearing and a single bad frost at blossom can take a whole year to zero, which an annual average never shows.',
    sources: ['Extension orchard yield tables', 'RHS fruit growing guides'],
  },
  {
    id: 'berry-hedge',
    name: 'Berry hedge',
    category: 'food',
    evidence: 'researched',
    summary: 'Raspberry, currant, gooseberry along a boundary. Uses edge space nothing else wants.',
    unitLabel: 'm of hedge',
    unitDefault: 12, unitMin: 1, unitMax: 200, unitStep: 1,
    footprintPerUnit: 1.5,
    siting: ['fullSun', 'partShade', 'openGround'],
    capitalPerUnit: 14,
    upkeepCostPerUnitPerMonth: 0.05,
    flows: [
      out('foodCalories', yearly(1600, 'growing')),
      out('foodProtein', yearly(0.04, 'growing')),
      need('waterIrrigation', flat(45)),
      need('labor', yearly(1.2)),
    ],
    notes: 'Roughly 3 kg per metre of well-managed hedge. Netting against birds is the difference between this number and nothing.',
    sources: ['Extension small-fruit yield guides'],
  },
  {
    id: 'laying-hens',
    name: 'Laying hens',
    category: 'food',
    evidence: 'researched',
    summary: 'The classic yard animal: eggs, manure, pest control and scrap disposal in one package.',
    unitLabel: 'hens',
    unitDefault: 6, unitMin: 2, unitMax: 60, unitStep: 1,
    footprintPerUnit: 2.5,
    siting: ['openGround', 'partShade'],
    capitalPerUnit: 95,
    upkeepCostPerUnitPerMonth: 3.2,
    flows: [
      out('foodCalories', yearly(18000, 'summer')),
      out('foodProtein', yearly(1.55, 'summer')),
      out('compost', flat(1.6)),
      need('animalFeed', flat(3.6)),
      need('organicWaste', flat(2), true),
      need('waterIrrigation', flat(7)),
      need('labor', flat(0.9)),
    ],
    notes: 'About 250 eggs per hen per year from a good layer, tailing off sharply after year two, and near zero in deep winter without light. Feed is the whole economics: 120 g/day per bird bought in is the default assumption here.',
    sources: ['Extension small-flock production data', 'USDA egg nutrient data'],
  },
  {
    id: 'meat-rabbits',
    name: 'Meat rabbits',
    category: 'food',
    evidence: 'researched',
    summary: 'The most protein per square metre per month of any yard livestock, on forage plus pellets.',
    unitLabel: 'does',
    unitDefault: 3, unitMin: 1, unitMax: 30, unitStep: 1,
    footprintPerUnit: 3,
    siting: ['partShade', 'openGround'],
    capitalPerUnit: 140,
    upkeepCostPerUnitPerMonth: 4.5,
    flows: [
      out('foodCalories', yearly(52000, 'growing')),
      out('foodProtein', yearly(6.5, 'growing')),
      out('compost', flat(2.4)),
      need('animalFeed', flat(9)),
      need('waterIrrigation', flat(15)),
      need('labor', flat(2.2)),
    ],
    notes: 'A doe producing four litters a year gives roughly 30 kg of dressed meat. Manure is the one livestock manure you can put straight on a bed without composting. Heat above 30 °C kills them and stops breeding.',
    sources: ['Extension rabbitry production figures', 'FAO, The Rabbit: Husbandry, Health and Production'],
  },
  {
    id: 'ducks',
    name: 'Ducks',
    category: 'food',
    evidence: 'researched',
    summary: 'Eggs and slug patrol. Tougher than hens in wet cold climates, and much harder on your ponds.',
    unitLabel: 'ducks',
    unitDefault: 4, unitMin: 2, unitMax: 40, unitStep: 1,
    footprintPerUnit: 3.5,
    siting: ['openGround', 'lowPoint'],
    capitalPerUnit: 85,
    upkeepCostPerUnitPerMonth: 3.4,
    flows: [
      out('foodCalories', yearly(19000, 'summer')),
      out('foodProtein', yearly(1.5, 'summer')),
      out('compost', flat(2)),
      need('animalFeed', flat(4.2)),
      need('waterIrrigation', flat(60)),
      need('labor', flat(1)),
    ],
    notes: 'Water use is the catch: they foul any standing water within days, so budget for changing it, and route the spill to a tree rather than a bed.',
    sources: ['Extension waterfowl production notes', 'Ashley English, Keeping Ducks'],
  },
  {
    id: 'beehive',
    name: 'Honeybee hive',
    category: 'food',
    evidence: 'researched',
    summary: 'Honey, wax, and pollination that quietly lifts every fruiting thing in the yard.',
    unitLabel: 'hives',
    unitDefault: 1, unitMin: 1, unitMax: 20, unitStep: 1,
    footprintPerUnit: 2,
    siting: ['fullSun', 'openGround'],
    capitalPerUnit: 420,
    upkeepCostPerUnitPerMonth: 3,
    flows: [
      out('foodCalories', yearly(60000, 'summer')),
      need('labor', yearly(22, 'growing')),
    ],
    notes: '20 kg of surplus honey at 3040 kcal/kg is a decent temperate hive in a decent year; a bad year is zero and a lost colony is negative. Varroa management is now a permanent part of the labour figure.',
    sources: ['National beekeeping association yield surveys'],
  },
  {
    id: 'mushroom-logs',
    name: 'Mushroom logs',
    category: 'food',
    evidence: 'researched',
    summary: 'Shiitake or oyster spawn plugged into fresh hardwood rounds in the shade.',
    unitLabel: 'logs',
    unitDefault: 10, unitMin: 2, unitMax: 200, unitStep: 2,
    footprintPerUnit: 0.3,
    siting: ['partShade'],
    capitalPerUnit: 7,
    upkeepCostPerUnitPerMonth: 0.05,
    flows: [
      out('foodCalories', yearly(340, 'growing')),
      out('foodProtein', yearly(0.09, 'growing')),
      need('biomass', yearly(2.5)),
      need('waterIrrigation', flat(8)),
      need('labor', yearly(0.4)),
    ],
    notes: 'About 1 kg of fresh mushrooms per log per year over a four-year productive life, starting a year after inoculation. Calorie-poor, protein-decent, and it turns coppice thinnings into food.',
    sources: ['Cornell Small Farms mushroom production guides'],
  },
  {
    id: 'aquaponics',
    name: 'Aquaponics loop',
    category: 'food',
    evidence: 'researched',
    summary: 'Fish tank plus grow beds on one recirculating pump. High output per m², and it fails hard when the power stops.',
    unitLabel: 'm² of grow bed',
    unitDefault: 10, unitMin: 2, unitMax: 120, unitStep: 1,
    footprintPerUnit: 2,
    siting: ['fullSun', 'indoor'],
    capitalPerUnit: 320,
    upkeepCostPerUnitPerMonth: 2.5,
    flows: [
      out('foodCalories', yearly(3600, 'growing')),
      out('foodProtein', yearly(0.9, 'growing')),
      need('electricity', flat(22)),
      need('animalFeed', flat(1.8)),
      need('waterIrrigation', flat(120)),
      need('labor', flat(2.5)),
    ],
    notes: 'The pump is life support: a day without power kills the fish and then the bacteria. Fish feed is usually bought, which quietly imports the fertility the system appears to generate.',
    sources: ['FAO, Small-scale Aquaponic Food Production', 'University aquaponics trial data'],
  },
  {
    id: 'root-cellar',
    name: 'Root cellar',
    category: 'food',
    evidence: 'researched',
    summary: 'Cool humid earth-buffered storage. Zero-energy preservation for roots, brassicas and apples.',
    unitLabel: 'm³ of cellar',
    unitDefault: 4, unitMin: 1, unitMax: 30, unitStep: 1,
    footprintPerUnit: 1.4,
    siting: ['openGround', 'nearHouse'],
    capitalPerUnit: 380,
    upkeepCostPerUnitPerMonth: 0.2,
    flows: [need('labor', flat(0.4))],
    storage: { resource: 'foodCalories', capacityPerUnit: 260000 },
    notes: 'Storage, not production — its whole job is carrying the autumn glut into February. 1 m³ holds roughly 350 kg of roots, and the calorie capacity here assumes a mixed load.',
    sources: ['Bubel, Root Cellaring', 'USDA storage condition tables'],
  },
  {
    id: 'bsf-larvae',
    name: 'Black soldier fly larvae',
    category: 'food',
    evidence: 'experimental',
    summary: 'Larvae that eat food waste fast and become high-protein poultry and fish feed.',
    unitLabel: 'bins',
    unitDefault: 1, unitMin: 1, unitMax: 10, unitStep: 1,
    footprintPerUnit: 1.2,
    siting: ['partShade', 'openGround'],
    capitalPerUnit: 180,
    upkeepCostPerUnitPerMonth: 0.5,
    flows: [
      need('organicWaste', flat(60)),
      out('animalFeed', flat(9)),
      out('compost', flat(12)),
      need('labor', flat(2)),
    ],
    notes: 'The conversion is real and well documented in the tropics. In a temperate yard the colony stalls below about 15 °C and usually has to be restarted every spring, so year-round output at yard scale is genuinely unproven.',
    sources: ['Published BSF bioconversion studies', 'Small-scale operator reports'],
  },
  {
    id: 'fodder-sprouts',
    name: 'Sprouted fodder trays',
    category: 'food',
    evidence: 'experimental',
    summary: 'Barley or wheat sprouted to a green mat in seven days to stretch bought feed.',
    unitLabel: 'trays in rotation',
    unitDefault: 7, unitMin: 3, unitMax: 60, unitStep: 1,
    footprintPerUnit: 0.35,
    siting: ['indoor'],
    capitalPerUnit: 22,
    upkeepCostPerUnitPerMonth: 4,
    flows: [
      out('animalFeed', flat(9)),
      need('waterIrrigation', flat(70)),
      need('electricity', flat(1.5)),
      need('labor', flat(1.6)),
    ],
    notes: 'The weight gain is mostly water: on a dry-matter basis sprouting usually *loses* a little feed value versus feeding the grain directly. It still helps palatability and vitamins in winter, but the "6x more feed" claim does not survive drying the sample. Kept as experimental for exactly that reason.',
    sources: ['Dry-matter analyses of hydroponic fodder', 'Extension fodder-system evaluations'],
  },
  {
    id: 'duckweed-pond',
    name: 'Duckweed / azolla pond',
    category: 'food',
    evidence: 'experimental',
    summary: 'Floating aquatic plants doubling every few days on nutrient-rich water, fed to poultry and fish.',
    unitLabel: 'm² of surface',
    unitDefault: 6, unitMin: 2, unitMax: 100, unitStep: 1,
    footprintPerUnit: 1.1,
    siting: ['fullSun', 'lowPoint'],
    capitalPerUnit: 25,
    upkeepCostPerUnitPerMonth: 0.1,
    flows: [
      out('animalFeed', yearly(9, 'growing')),
      need('waterIrrigation', flat(40)),
      need('blackwater', flat(30), true),
      need('labor', flat(0.8)),
    ],
    notes: 'Laboratory growth rates are spectacular and yard ponds rarely come close — the limit is nitrogen supply, shading and temperature. Feeding on-farm greens grown on human waste also carries a pathogen question you should answer before it reaches the food chain.',
    sources: ['FAO duckweed aquaculture papers', 'Azolla trial reports'],
  },

  /* ============================ SANITATION ============================ */
  {
    id: 'composting-toilet',
    name: 'Composting toilet',
    category: 'sanitation',
    evidence: 'researched',
    summary: 'Urine-diverting dry toilet. Removes the largest single water demand in most houses.',
    unitLabel: 'people served',
    unitDefault: 3, unitMin: 1, unitMax: 12, unitStep: 1,
    footprintPerUnit: 0.5,
    siting: ['indoor', 'nearHouse'],
    capitalPerUnit: 320,
    upkeepCostPerUnitPerMonth: 1.5,
    flows: [
      need('blackwater', flat(900)),
      out('waterIrrigation', flat(750)),
      out('compost', flat(4)),
      need('biomass', flat(3)),
      need('labor', flat(1.6)),
    ],
    notes: 'Diverting a flush toilet saves roughly 30 L per person per day — often a fifth of household water. Cover material (sawdust, leaf mould) is a real ongoing input people forget. Legality varies enormously by jurisdiction.',
    sources: ['Del Porto & Steinfeld, The Composting Toilet System Book'],
  },
  {
    id: 'humanure-system',
    name: 'Thermophilic humanure system',
    category: 'sanitation',
    evidence: 'researched',
    summary: 'Bucket collection into a managed hot compost pile with a long curing period.',
    unitLabel: 'people served',
    unitDefault: 3, unitMin: 1, unitMax: 10, unitStep: 1,
    footprintPerUnit: 1.5,
    siting: ['openGround'],
    capitalPerUnit: 110,
    upkeepCostPerUnitPerMonth: 0.5,
    flows: [
      need('blackwater', flat(900)),
      out('waterIrrigation', flat(750)),
      out('compost', flat(7)),
      need('biomass', flat(5)),
      need('labor', flat(3.2)),
    ],
    notes: 'The method is thoroughly documented and works, but it is entirely dependent on operator discipline: reach thermophilic temperatures, cure for a year, and keep it away from food crops until it has. Sloppy operation is a genuine pathogen risk, not a theoretical one.',
    sources: ['Jenkins, The Humanure Handbook'],
  },
  {
    id: 'septic-leachfield',
    name: 'Septic tank & leach field',
    category: 'sanitation',
    evidence: 'researched',
    summary: 'The conventional answer. Handles everything, returns nothing but disposal.',
    unitLabel: 'systems',
    unitDefault: 1, unitMin: 1, unitMax: 2, unitStep: 1,
    footprintPerUnit: 35,
    siting: ['openGround', 'lowPoint'],
    capitalPerUnit: 6500,
    upkeepCostPerUnitPerMonth: 12,
    flows: [
      need('blackwater', flat(9000)),
      need('labor', flat(0.3)),
    ],
    notes: 'In the model this is a sink: it absorbs blackwater and produces nothing. That is the honest comparison against a composting toilet, which absorbs the same flow and hands back fertility.',
    sources: ['EPA onsite wastewater treatment manual', 'Installed cost surveys'],
  },
  {
    id: 'worm-flush-toilet',
    name: 'Vermifilter flush toilet',
    category: 'sanitation',
    evidence: 'experimental',
    summary: 'A flush toilet draining into a worm bed that digests solids in place.',
    unitLabel: 'people served',
    unitDefault: 3, unitMin: 1, unitMax: 10, unitStep: 1,
    footprintPerUnit: 2.5,
    siting: ['openGround', 'nearHouse'],
    capitalPerUnit: 900,
    upkeepCostPerUnitPerMonth: 1,
    flows: [
      need('blackwater', flat(900)),
      out('compost', flat(3)),
      out('waterIrrigation', flat(400)),
      need('labor', flat(0.8)),
    ],
    notes: 'Promising and in use in a handful of places, but the peer-reviewed base at household scale is thin and effluent quality varies with loading and temperature. Do not put the output on food crops on the strength of this catalog entry.',
    sources: ['Small-number vermifilter field trials', 'Operator reports'],
  },

  /* ============================ SOIL ============================ */
  {
    id: 'compost-bays',
    name: 'Three-bay compost',
    category: 'soil',
    evidence: 'researched',
    summary: 'Hot-composting bays turning garden residue and kitchen waste into the fertility every bed above depends on.',
    unitLabel: 'm³ of bay',
    unitDefault: 3, unitMin: 1, unitMax: 24, unitStep: 1,
    footprintPerUnit: 1.3,
    siting: ['partShade', 'openGround'],
    capitalPerUnit: 60,
    upkeepCostPerUnitPerMonth: 0,
    flows: [
      need('organicWaste', flat(38)),
      need('biomass', flat(10), true),
      out('compost', flat(14)),
      need('waterIrrigation', flat(30)),
      need('labor', flat(1.4)),
    ],
    notes: 'Roughly a third of what goes in comes out as finished compost; the rest leaves as CO₂ and water. If your beds demand more compost than your bays produce, the design is importing fertility whether or not you noticed.',
    sources: ['Cornell composting engineering references', 'Extension composting guides'],
  },
  {
    id: 'vermicompost',
    name: 'Worm bin',
    category: 'soil',
    evidence: 'researched',
    summary: 'Cool composting of kitchen waste by worms. Small volume, high-quality output, works indoors.',
    unitLabel: 'm² of bin',
    unitDefault: 1, unitMin: 0.5, unitMax: 12, unitStep: 0.5,
    footprintPerUnit: 1.1,
    siting: ['partShade', 'indoor'],
    capitalPerUnit: 90,
    upkeepCostPerUnitPerMonth: 0.2,
    flows: [
      need('organicWaste', flat(14)),
      out('compost', flat(6)),
      need('labor', flat(0.8)),
    ],
    notes: 'A worm bin handles about half a kilo of scraps per m² per day. It will not touch woody garden waste — that needs the bays.',
    sources: ['Appelhof, Worms Eat My Garbage', 'Extension vermicomposting guides'],
  },
  {
    id: 'chop-and-drop',
    name: 'Comfrey & chop-and-drop',
    category: 'soil',
    evidence: 'researched',
    summary: 'Deep-rooted nutrient accumulators cut several times a season and dropped where they grow.',
    unitLabel: 'm² planted',
    unitDefault: 20, unitMin: 2, unitMax: 400, unitStep: 2,
    footprintPerUnit: 1,
    siting: ['partShade', 'fullSun', 'openGround'],
    capitalPerUnit: 4,
    upkeepCostPerUnitPerMonth: 0,
    flows: [
      out('biomass', yearly(3.2, 'growing')),
      out('compost', yearly(1.8, 'growing')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.4)),
      need('labor', yearly(0.5, 'growing')),
    ],
    notes: 'The cheapest mulch and compost feedstock there is, but "nutrient accumulation" mostly means moving minerals up from the subsoil of the same site, not creating them. It still has to come from somewhere.',
    sources: ['Comfrey trial data', 'Toensmeier, Perennial Vegetables'],
  },
  {
    id: 'cover-crop',
    name: 'Cover crop rotation',
    category: 'soil',
    evidence: 'researched',
    summary: 'Legumes and grasses grown to be turned in — fertility built in place rather than carted in.',
    unitLabel: 'm² in rotation',
    unitDefault: 30, unitMin: 5, unitMax: 800, unitStep: 5,
    footprintPerUnit: 0,
    siting: ['openGround', 'fullSun'],
    capitalPerUnit: 0.6,
    upkeepCostPerUnitPerMonth: 0.01,
    flows: [
      out('compost', yearly(2.2, 'growing')),
      out('biomass', yearly(0.9, 'growing')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.25)),
      need('labor', yearly(0.25, 'growing')),
    ],
    notes: 'Zero extra footprint because it occupies beds between cash crops — but it does occupy them, so a bed under cover crop is a bed not producing food that month.',
    sources: ['SARE, Managing Cover Crops Profitably'],
  },
  {
    id: 'biochar-kiln',
    name: 'Biochar kiln',
    category: 'soil',
    evidence: 'experimental',
    summary: 'Cone or retort kiln converting woody waste into a stable carbon soil amendment.',
    unitLabel: 'kilns',
    unitDefault: 1, unitMin: 1, unitMax: 4, unitStep: 1,
    footprintPerUnit: 4,
    siting: ['openGround'],
    capitalPerUnit: 350,
    upkeepCostPerUnitPerMonth: 0.5,
    flows: [
      need('biomass', flat(40)),
      out('compost', flat(9)),
      need('labor', flat(3)),
    ],
    notes: 'The chemistry is solid; the yard-scale agronomic payback is not. Response ranges from large on weathered tropical soils to nil or negative on good temperate loam, and raw char must be charged with nutrients first or it robs the bed in year one.',
    sources: ['Meta-analyses of biochar yield response', 'Ithaka Institute kiln documentation'],
  },
  {
    id: 'bokashi',
    name: 'Bokashi fermentation',
    category: 'soil',
    evidence: 'experimental',
    summary: 'Anaerobic bran-inoculated fermentation of all food waste, including meat and dairy.',
    unitLabel: 'buckets in rotation',
    unitDefault: 2, unitMin: 1, unitMax: 12, unitStep: 1,
    footprintPerUnit: 0.2,
    siting: ['indoor', 'nearHouse'],
    capitalPerUnit: 45,
    upkeepCostPerUnitPerMonth: 3,
    flows: [
      need('organicWaste', flat(18)),
      out('compost', flat(11)),
      need('labor', flat(0.9)),
    ],
    notes: 'Fermenting is not composting: the output is pickled waste that still has to be buried or composted before a plant can use it, and it is acidic on the way in. The high mass yield here is honest about weight and misleading about readiness — which is exactly why it is not tiered higher.',
    sources: ['Bokashi method literature', 'Independent decomposition comparisons'],
  },

  /* ============================ SHELTER ============================ */
  {
    id: 'attached-greenhouse',
    name: 'Attached greenhouse',
    category: 'shelter',
    evidence: 'researched',
    summary: 'A glazed south-facing room that grows food and dumps its surplus heat into the house.',
    unitLabel: 'm² of floor',
    unitDefault: 12, unitMin: 4, unitMax: 80, unitStep: 2,
    footprintPerUnit: 1,
    siting: ['nearHouse', 'fullSun'],
    capitalPerUnit: 420,
    upkeepCostPerUnitPerMonth: 0.4,
    flows: [
      out('foodCalories', yearly(2600, 'flat')),
      out('foodProtein', yearly(0.14, 'flat')),
      out('heat', driven('peakSunHours', 0.22)),
      need('waterIrrigation', driven('irrigationDemandPerM2', 1.3)),
      need('compost', yearly(8)),
      need('labor', yearly(3.5)),
    ],
    notes: 'Two systems in one envelope, which is the appeal — and the risk, since it also leaks house heat back out on winter nights unless it is separated by an insulated wall and a door you actually close.',
    sources: ['Passive solar greenhouse design literature', 'Extension high-tunnel yield data'],
  },
  {
    id: 'thermal-mass-wall',
    name: 'Thermal mass / trombe wall',
    category: 'shelter',
    evidence: 'researched',
    summary: 'Dark glazed masonry that soaks up winter sun during the day and releases it after dark.',
    unitLabel: 'm² of wall',
    unitDefault: 8, unitMin: 2, unitMax: 40, unitStep: 1,
    footprintPerUnit: 0.4,
    siting: ['nearHouse', 'fullSun'],
    capitalPerUnit: 260,
    upkeepCostPerUnitPerMonth: 0.05,
    flows: [
      out('heat', driven('peakSunHours', 0.3)),
      need('labor', flat(0.05)),
    ],
    notes: 'Only pays off on a genuinely sunny winter-facing wall; on an oceanic-climate site with 1 sun-hour in January it does very little. That is why the number is climate-driven rather than a flat annual figure.',
    sources: ['Passive solar design references', 'Trombe wall performance studies'],
  },
  {
    id: 'shade-structure',
    name: 'Shade structure / vine pergola',
    category: 'shelter',
    evidence: 'researched',
    summary: 'Deciduous vine on a frame: shades the wall in summer, drops its leaves and lets the sun back in.',
    unitLabel: 'm² of cover',
    unitDefault: 10, unitMin: 2, unitMax: 60, unitStep: 1,
    footprintPerUnit: 1,
    siting: ['nearHouse', 'fullSun'],
    capitalPerUnit: 55,
    upkeepCostPerUnitPerMonth: 0.05,
    flows: [
      out('foodCalories', yearly(900, 'growing')),
      out('biomass', yearly(0.8, 'winter')),
      need('waterIrrigation', driven('irrigationDemandPerM2', 0.4)),
      need('labor', yearly(1)),
    ],
    notes: 'The cooling benefit is real but not modelled here, since the engine has no indoor temperature — treat the grapes or kiwi as the countable part and the comfort as a bonus.',
    sources: ['Urban shading studies', 'Extension grape yield tables'],
  },
  {
    id: 'water-pond',
    name: 'Lined pond',
    category: 'water',
    evidence: 'researched',
    summary: 'Open water: irrigation reserve, fire supply, habitat and thermal buffer.',
    unitLabel: 'm² of surface',
    unitDefault: 15, unitMin: 3, unitMax: 300, unitStep: 1,
    footprintPerUnit: 1.15,
    siting: ['lowPoint', 'fullSun', 'openGround'],
    capitalPerUnit: 55,
    upkeepCostPerUnitPerMonth: 0.1,
    flows: [
      out('waterIrrigation', driven('rainfallMm', 1)),
      need('waterIrrigation', driven('irrigationDemandPerM2', 1.15)),
      need('labor', flat(0.05)),
    ],
    storage: { resource: 'waterIrrigation', capacityPerUnit: 800 },
    notes: 'Catches every millimetre that falls on it and evaporates more than a bed does — in an arid climate the model will show it running a net loss, which is the correct and frequently ignored answer. Assumed 0.8 m deep for storage.',
    sources: ['Farm pond design references', 'Open-water evaporation coefficients'],
  },
];

export const CATALOG_BY_ID: Record<string, SystemDef> =
  Object.fromEntries(CATALOG.map((s) => [s.id, s]));
